# Параметры CreditDataPreprocessor
NumberOfDependents_fill_value: 0
NumberOfDependents_up_threshold: 10
MonthlyIncome_fill_value: 0
RevolvingUtilizationOfUnsecuredLines_drop_threshold: 2
age_low_drop_threshold: 18
age_up_drop_threshold: 80
DebtRatio_up_threshold: 5
PastDueRiskScore_weights: [1.0, 1.2, 1.3]
NumberRealEstateLoansOrLines_drop_threshold: 20
drop_special_codes: false