params:
  # Core parameters
  iterations: 100
  learning_rate: 0.03
  depth: 6
  l2_leaf_reg: 3.0
  random_strength: 1.0
  one_hot_max_size: 2
  border_count: 128
  scale_pos_weight: 1.0
  bagging_temperature: 1.0
  thread_count: -1
  random_seed: 42
  verbose: 0
  boosting_type: 'Plain'
  grow_policy: 'SymmetricTree'
  task_type: 'CPU'

use_cv: false

cv_params:
  estimator: null
  param_grid:
     iterations: [100,200,300,500]
#    depth: [4, 6, 8]
#    learning_rate: [0.03, 0.05, 0.1]
#    # Bagging
#    subsample: [0.8, 1.0]
#    # Feature sampling
#    rsm: [0.8, 1.0]
#    # Boosting
#    boosting_type: ['Plain', 'Ordered']
#     # Regularization
#    l2_leaf_reg: [1.0, 3.0, 5.0, 7.0]
#    bagging_temperature: [0.5, 1.0, 2.0, 5.0]
#    random_strength: [0.5, 1.0, 2.0, 5.0]

  scoring: 'roc_auc'
  n_jobs: -1
  refit: true
  cv: 5
  verbose: 0
  pre_dispatch: '2*n_jobs'
  return_train_score: false