params:
  criterion: 'gini'
  splitter: 'best'
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: null
  random_state: 42
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  class_weight: 'balanced'
  ccp_alpha: 0.0
  monotonic_cst: null

use_cv: false

cv_params:
  estimator: null
  param_grid:
    criterion: ['gini', 'entropy', 'log_loss']
    splitter: ['best', 'random']
    max_depth: [3, 5, 7, 8, 10, 15, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4, 6, 8, 10]
#    min_weight_fraction_leaf: 0.0
#    max_features: null
#    random_state: null
#    max_leaf_nodes: null
    min_impurity_decrease: [0.0, 0.001, 0.005, 0.01]
#    class_weight: null
#    ccp_alpha: 0.0
#    monotonic_cst: null
  scoring: 'roc_auc'
  n_jobs: -1
  refit: true
  cv: 5
  verbose: 0
  pre_dispatch: '2*n_jobs'
  #error_score: np.nan
  return_train_score: false
