params:
  # Core parameters
  boosting_type: 'gbdt' # 'gbdt', 'dart', 'goss'
  objective: 'binary'
  num_iterations: 100  # n_estimators
  learning_rate: 0.1
  num_leaves: 31
  max_depth: -1  # no limit
  
  # Data parameters
  min_data_in_leaf: 20  # min_child_samples
  min_sum_hessian_in_leaf: 1e-3  # min_child_weight
  bagging_fraction: 1.0  # subsample
  bagging_freq: 0  # no bagging
  feature_fraction: 1.0  # colsample_bytree
  feature_fraction_bynode: 1.0  # colsample_bylevel
  
  # Regularization
  lambda_l1: 0.0
  lambda_l2: 0.0
  min_gain_to_split: 0.0
  
  # Class imbalance
  scale_pos_weight: 1.0
  
  # System parameters
  num_threads: -1  # default: 0 (auto), -1 means all cores (n_jobs)
  device_type: 'cpu'
  seed: 42
  verbose: -1  # default: 1 (warning), -1 = silent
  deterministic: false

use_cv: false

cv_params:
  estimator: null
  param_grid:
    'learning_rate': [0.03, 0.05, 0.07, 0.1, 0.2]
    'n_estimators': [100, 200, 300, 500, 700, 1000]
#   Basic tree structure
#    num_leaves: [31, 63, 95]
#    max_depth: [-1, 7, 10]
#    learning_rate: [0.03, 0.05, 0.1]
#    min_data_in_leaf: [20, 30]

#    # Sampling
#    bagging_fraction: [0.8, 1.0]
#    bagging_freq: [1, 3]
#    feature_fraction: [0.8, 1.0]

#    # Regularization
#    lambda_l1: [0.0, 0.1, 1.0]
#    lambda_l2: [1.0, 2.0]
#    min_gain_to_split: [0.0, 0.1]
#    min_sum_hessian_in_leaf: [1e-3, 1e-1]





  scoring: 'roc_auc'
  n_jobs: -1
  refit: true
  cv: 5
  verbose: 0
  pre_dispatch: '2*n_jobs'
  return_train_score: false