params:
  C: 1.0
  penalty: "l2"
  solver: "lbfgs"
  max_iter: 2000
  class_weight: "balanced"
  random_state: 42
  n_jobs: -1

use_cv: false

cv_params:
  cv: 5
  scoring: "roc_auc"
  Cs: [0.001, 0.01, 0.1, 1, 10, 100, 1000]
  l1_ratios: null
  penalty: "l2" # ‘l1’, ‘l2’, ‘elasticnet’
  solver: "lbfgs" # ‘lbfgs’, ‘liblinear’, ‘newton-cg’, ‘newton-cholesky’, ‘sag’, ‘saga’
  class_weight: 'balanced'
