params:
  n_estimators: 300
  criterion: 'gini'
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: 'sqrt'
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  bootstrap: true
  oob_score: false
  n_jobs: -1
  random_state: 42
  verbose: 0
  warm_start: false
  class_weight: 'balanced'
  ccp_alpha: 0.0
  max_samples: null
  monotonic_cst: null

use_cv: false

cv_params:
  estimator: null
  param_grid:
    n_estimators: [100,200,300,500,1000]
#    criterion: ['gini', 'entropy', 'log_loss']
#    max_depth: [8, 10, 15, null]
#    min_samples_split: [2, 10]
#    min_samples_leaf: [1, 4]
#    min_weight_fraction_leaf: 0.0
#    max_features: 'sqrt'
#    max_leaf_nodes: null
#    min_impurity_decrease: 0.0
#    bootstrap: true
#    oob_score: false
#    n_jobs: null
#    random_state: null
#    verbose: 0
#    warm_start: false
#    class_weight: null
#    ccp_alpha: 0.0
#    max_samples: null
#    monotonic_cst: null
  scoring: 'roc_auc'
  n_jobs: -1
  refit: true
  cv: 5
  verbose: 0
  pre_dispatch: '2*n_jobs'
  #error_score: np.nan
  return_train_score: false

