params:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.3
  subsample: 1.0
  colsample_bytree: 1.0
  colsample_bylevel: 1.0
  colsample_bynode: 1.0
  reg_alpha: 0.0
  reg_lambda: 1.0
  gamma: 0.0
  min_child_weight: 1
  objective: 'binary:logistic'
  booster: 'gbtree'
  tree_method: 'auto' # 'auto', 'exact', 'approx', 'hist', 'gpu_hist'
  scale_pos_weight: 1 # аналог class_weight
  random_state: 42
  n_jobs: -1
  verbosity: 0

use_cv: false

cv_params:
  estimator: null
  param_grid:
    n_estimators: [100, 300, 500]
#    max_depth: [4, 6, 8, 10]
#    learning_rate: [0.01, 0.05, 0.1, 0.2]
#    subsample: [0.6, 0.8, 1.0]
#    colsample_bytree: [0.6, 0.8, 1.0]
#    min_child_weight: [1, 3, 5]
#    reg_alpha: [0.0, 0.1, 1.0]
#    reg_lambda: [1.0, 1.5, 2.0]
  scoring: 'roc_auc'
  n_jobs: -1
  refit: true
  cv: 5
  verbose: 0
  pre_dispatch: '2*n_jobs'
  return_train_score: false

